# Generated by Django 5.2 on 2025-04-27 00:13

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('poligono', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'db_table': 'zonariesgo',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asalto', 'Asalto'), ('choque', 'Choque'), ('homicidio', 'Homicidio'), ('robo', 'Robo'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('fecha_incidente', models.DateTimeField()),
                ('hora_incidente', models.TimeField()),
                ('latitud', models.FloatField(default=0.0)),
                ('longitud', models.FloatField(default=0.0)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('gravedad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('no_resuelto', 'No Resuelto')], default='no_resuelto', max_length=20)),
                ('zona_riesgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zonariesgo')),
            ],
            options={
                'db_table': 'incidente',
                'indexes': [models.Index(fields=['latitud', 'longitud'], name='incidente_latitud_c753c7_idx'), models.Index(fields=['fecha_incidente'], name='incidente_fecha_i_010bf2_idx'), models.Index(fields=['gravedad'], name='incidente_graveda_98fc4e_idx')],
            },
        ),
    ]
