# Generated by Django 5.2 on 2025-04-27 05:19

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('assault', 'Asalto'), ('crash', 'Choque'), ('homicide', 'Homicidio'), ('robbery', 'Robo'), ('other', 'Otro')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_datetime', models.DateTimeField(auto_now_add=True)),
                ('report_time', models.TimeField(auto_now_add=True)),
                ('incident_datetime', models.DateTimeField()),
                ('incident_time', models.TimeField()),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('severity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('status', models.CharField(choices=[('in_progress', 'En Proceso'), ('resolved', 'Resuelto'), ('unresolved', 'No Resuelto')], default='unresolved', max_length=20)),
            ],
            options={
                'db_table': 'incident',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='incident_latitud_eb09f5_idx'), models.Index(fields=['incident_datetime'], name='incident_inciden_20b186_idx'), models.Index(fields=['severity'], name='incident_severit_259ce9_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Incidente',
        ),
        migrations.DeleteModel(
            name='ZonaRiesgo',
        ),
    ]
