# Generated by Django 5.2 on 2025-04-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250427_0715'),
    ]

    operations = [
    ]
