# Generated by Django 5.2 on 2025-04-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_incidente_ubicacion_incidente_location'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incidente',
            new_name='incidentes_latitud_360581_idx',
            old_name='core_incide_latitud_b3a14a_idx',
        ),
        migrations.RenameIndex(
            model_name='incidente',
            new_name='incidentes_fecha_i_184756_idx',
            old_name='core_incide_fecha_i_0174ba_idx',
        ),
        migrations.RenameIndex(
            model_name='incidente',
            new_name='incidentes_graveda_b8939c_idx',
            old_name='core_incide_graveda_8e6bbb_idx',
        ),
        migrations.AlterModelTable(
            name='incidente',
            table='incidentes',
        ),
        migrations.AlterModelTable(
            name='zonariesgo',
            table='zonariesgo',
        ),
    ]
