# Generated by Django 5.2 on 2025-04-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250427_0716'),
    ]

    operations = [
    ]
