# Generated by Django 5.2 on 2025-04-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_core_incide_latitud_b3a14a_idx_incidentes_latitud_360581_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incidente',
            new_name='incidente_latitud_c753c7_idx',
            old_name='incidentes_latitud_360581_idx',
        ),
        migrations.RenameIndex(
            model_name='incidente',
            new_name='incidente_fecha_i_010bf2_idx',
            old_name='incidentes_fecha_i_184756_idx',
        ),
        migrations.RenameIndex(
            model_name='incidente',
            new_name='incidente_graveda_98fc4e_idx',
            old_name='incidentes_graveda_b8939c_idx',
        ),
        migrations.AlterModelTable(
            name='incidente',
            table='incidente',
        ),
    ]
